name: resq
description: "A Disaster Management Tool."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=3.7.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  google_fonts: ^6.2.1
  path_provider: ^2.0.0
  universal_html: ^2.2.4
  pdf: ^3.10.7
  printing: ^5.11.1
  flutter_svg: ^2.0.9
  syncfusion_flutter_datagrid: ^28.2.12
  provider: ^6.0.5
  open_file: ^3.3.1


  # Firebase

  # UI and Icons
  cupertino_icons: ^1.0.8

  # HTTP Requests
  http: ^1.1.0  
  http_parser: ^4.1.2
  firebase_core: ^3.12.1

  # Charts & Graphs
  fl_chart: ^0.70.2

  # Secure Storage
  flutter_secure_storage: ^9.2.2

  # Internationalization
  intl: ^0.20.2

  # Image Picker
  image_picker: ^1.0.4
  dio: ^5.1.0
  
  

  # File Handling & Permissions
  file_picker: ^9.1.0
  path: ^1.8.2
  permission_handler: ^11.4.0
  
  excel: ^4.0.6

 # Dependency for fetching location
  geolocator: ^9.0.1

  # Persistent Storage
  shared_preferences: ^2.2.2

  

  # URL Handling
  url_launcher: ^6.1.14
  connectivity_plus: ^5.0.2
  # Excel Handling
  syncfusion_flutter_xlsio: ^28.2.11
  # Persistent Storage
  firebase_auth: ^5.5.1

  # Google Maps and Geocoding
  google_maps_flutter: ^2.1.1
  geocoding: ^3.0.0

  syncfusion_flutter_charts: 28.2.11
  firebase_storage: ^12.4.4
  cloud_firestore: ^5.6.5
  flutter_xlider: ^3.5.0
  file_saver: ^0.2.14
  
  
  csv: ^5.0.0
  share_plus: ^7.0.0
  firebase_messaging: ^15.2.5
  flutter_local_notifications: ^19.0.0
  flutter_dotenv: ^5.2.1
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0


  

flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  assets:
    - ./assets/images/
    - gmap.env
  

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/to/asset-from-package

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
