name: resq
description: "A Disaster Management Tool."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.7.0-209.1.beta
dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter

  # UI and Icons
  cupertino_icons: ^1.0.8
  http: ^0.13.6  
  http_parser: ^4.1.2
  firebase_core: ^3.12.1



  # Charts & Graphs
  fl_chart: ^0.63.0

  # Secure Storage
  flutter_secure_storage: ^9.0.0

  # Internationalization
  intl: ^0.18.1

  # Image Picker
  image_picker: ^1.0.4

  # persistent storage
  shared_preferences: ^2.2.0
  firebase_auth: ^5.5.1




dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  

flutter:
  uses-material-design: true