name: resq
description: "A Disaster Management Tool."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=3.7.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter

  # Firebase
  firebase_auth: ^4.16.0
  firebase_core: ^2.27.2

  # UI and Icons
  cupertino_icons: ^1.0.8

  # HTTP Requests
  http: ^1.1.0  
  http_parser: ^4.1.2

  # Charts & Graphs
  fl_chart: ^0.70.2

  # Secure Storage
  flutter_secure_storage: ^9.2.2

  # Internationalization
  intl: ^0.20.2

  # Image Picker
  image_picker: ^1.0.4

  # File Handling & Permissions
  file_picker: ^8.0.7
  path: ^1.8.2
  permission_handler: ^11.4.0
  
  excel: ^2.0.0

  # Persistent Storage
  shared_preferences: ^2.2.2

  # URL Handling
  url_launcher: ^6.1.14

  # Excel Handling
  syncfusion_flutter_xlsio: ^28.2.11
  path_provider: ^2.1.2

  syncfusion_flutter_charts: 28.2.11
  firebase_storage: ^11.0.0
  cloud_firestore: ^4.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/